name: 'Setup FPC environment'

description: 'Setup a Free Pascal Compiler and add it to the PATH'

inputs:
  fpc-version:
    description: 'Version of required FPC'
    required: false
    default: 'stable'

runs:
  using: "composite"
  steps:
    - name: Fetching FPC bundle
      run: |
          mkdir ${{ github.workspace }}\.fpc
          curl -H "Authorization: token ${{ github.token }}" -H "Accept: application/vnd.github.v3.raw" https://github.com/visualdoj/free-pascal-compiler-builds/releases/download/v0.1-alpha/release_3_2_2.zip --output ${{ github.workspace }}\.fpc\release_3_2_2.zip
      shell: cmd
    
    - name: Unpacking FPC
      run: Expand-Archive -LiteralPath ${{ github.workspace }}\.fpc\release_3_2_2.zip -DestinationPath ${{ github.workspace }}\.fpc\release_3_2_2
      shell: powershell
